### ISSUE TITLE
minikube can't pull images from nexus

### ISSUE THREAD

**Issue by bak0al3x** [bak0al3x/dotnet-adventure#13]
Nexus 3 is running inside a docker container on my development machine.

Outside of the localhost it is accessible via the `http://192.168.98.170:8082` URL.

The idea is to store the docker images here which were build by `TeamCity`, and during the `CD`
phase deploy Pods from them.

What is working:
- After `docker login` on my local machine with my local `Docker` agent I can push and pull images to/from the Nexus3
Docker registry
- Directly from the `minikube` host (which is using `Docker` as a hypervisor), after `docker login` I can do the same

What is not working:
- When I want to create a simple Pod using a `192.168.98.170:8082/example-image:example-tag` I always got 
`ErrImagePull` error.

Minikube shoulbe be able to access the Docker repositories of the Nexus 3.

**Comment by bak0al3x** [comment]
It took me a long time to figure this out, but here is the solution.

### Step 1. Start the `Minikube` with the proper settings.

Not 100% percent sure if this is a must, but when I could solve the issue I've started the `minikube` vm with the
following flags: `--insecure-registry=192.168.98.170:8082,192.168.98.170:8083`

After it started I went to the machine, and checked the `Docker` service if it did pick up those settings:

```bash
docker@minikube:~$ systemctl status docker
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2022-03-09 20:22:02 UTC; 18min ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
   Main PID: 397 (dockerd)
      Tasks: 47
     Memory: 1.9G
        CPU: 51.216s
     CGroup: /system.slice/docker.service
             ├─ 397 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/serv
er-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 --insecure-registry 192.168.98.170:8082 --insecure-registry 192.168.98.170:8083
             ├─4104 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5000 -container-ip 172.17.0.4 -container-port 80
             ├─4809 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 443 -container-ip 172.17.0.3 -container-port 443
             └─4823 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 80 -container-ip 172.17.0.3 -container-port 80
```

You can see from the output of the command above, that both of those registries were added as insecure registries.

### Step 2. Create a secret in `Kubernetes` for image pulling

You can create a `docker-registry` type of Secret in Kubernetes. Once you have that, you can use that secret during
the image pulling.

#### 2.1. Creating the Secret:

```bash
kubectl create secret docker-registry regcred \
    --docker-server=<your-registry-server> \
    --docker-username=<your-name> \
    --docker-password=<your-pword>
```

#### 2.2. Create a Deployment which utilizes this Secret:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    app: sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: sample
        image: 192.168.98.170:8082/sail-app:8.1
        ports:
        - containerPort: 80
```

*Note that `imagePullSecrets` field.*

Once those steps are completed I could deploy my example application, there were no `ErrImagePull` errors anymore:

```bash
kubectl get pods
NAME                      READY   STATUS    RESTARTS   AGE
sample-548d4bc55d-tfb98   1/1     Running   0          14m
```
